In [7]:
import pandas as pd
import numpy as np

In [6]:
Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

time = pd.array([10, 20, 30, 15, 5, 40,20, 8, 20])
result = pd.array(Hut_Paradise_DF['5.Demo two weeks']*time).sum()
result

1348

In [10]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

a = 2*v - 3*w
a

array([-3, 14,  3,  4,  2])

In [18]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).transpose()
Cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).transpose()
Inc - Inc*0.13 - Cons

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [47]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [50]:
#прибыль салона
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
P = Price_DF.values
C = Count_DF.values
salon_inc = (P*C)@(com)
print(salon_inc)

[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


In [54]:
#прибыль стилистов
styler_inc = P*C@(np.ones(5)-com)
styler_inc

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [64]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
A = np.array([v1, v2, v3, v4]).transpose()
rank = np.linalg.matrix_rank(A) #ранг матрицы
G = A.transpose()@A #матрица Грама
det = np.linalg.det(G) #определитель матрицы
G_inv = np.linalg.inv(G) #обратная матрица
G_inv

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [73]:
x_1 = np.array([5.1, 1.8, 2.1, 10.3, 12.1, 12.6])
x_2 = np.array([10.2, 3.7, 4.1, 20.5, 24.2, 24.1])
x_3 = np.array([2.5, 0.9, 1.1, 5.1, 6.1, 6.3])
C = np.corrcoef([x_1, x_2, x_3])
print('Rank:', np.linalg.matrix_rank(C))
print('Determinant: {:.7f}'.format(np.linalg.det(C)))
print(C)

Rank: 3
Determinant: 0.0000005
[[1.         0.99925473 0.99983661]
 [0.99925473 1.         0.99906626]
 [0.99983661 0.99906626 1.        ]]


In [74]:
A = np.array([
    [1, 1, 1, 1],
    [1, 3, -2, 9],
    [1, 9, 4, 81]
    
]).T
y = np.array([3, 7, -5, 21])
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(w_hat)

[ 0.11446013  2.46095638 -0.01608801]


In [91]:
transaction = pd.read_csv('data/transaction2.csv', sep=';')
product = pd.read_csv('data/product.csv', sep=';')

In [99]:
merged = transaction.merge(
    product,
    on=['product_id', 'brand', 'product_line', 'product_class', 'product_size'],
    how='left'
)
display(merged.sort_values(by='transaction_id'))

transaction_id  product_id  customer_id transaction_date online_order   
0                   1           2         2950       25.02.2017        False  \
1                   2           3         3120       21.05.2017         True   
2                   3          37          402       16.10.2017        False   
3                   4          88         3135       31.08.2017        False   
4                   5          78          787       01.10.2017         True   
...               ...         ...          ...              ...          ...   
19995           19996          51         1018       24.06.2017         True   
19996           19997          41          127       09.11.2017         True   
19997           19998          87         2284       14.04.2017         True   
19998           19999           6         2764       03.07.2017        False   
19999           20000          11         1144       22.09.2017         True   

      order_status           brand product_line product_class product_size   
0         Approved           Solex     Standard        medium       medium  \
1         Approved   Trek Bicycles     Standard        medium        large   
2         Approved      OHM Cycles     Standard           low       medium   
3         Approved  Norco Bicycles     Standard        medium       medium   
4         Approved  Giant Bicycles     Standard        medium        large   
...            ...             ...          ...           ...          ...   
19995     Approved      OHM Cycles     Standard          high       medium   
19996     Approved           Solex         Road        medium       medium   
19997     Approved      OHM Cycles     Standard        medium       medium   
19998     Approved      OHM Cycles     Standard          high       medium   
19999     Approved   Trek Bicycles     Standard        medium        small   

       list_price  Unnamed: 11  new_product_id  
0           71.49          NaN            22.0  
1         2091.47          NaN            23.0  
2         1793.43          NaN            83.0  
3         1198.46          NaN           165.0  
4         1765.30          NaN           148.0  
...           ...          ...             ...  
19995     2005.66          NaN           105.0  
19996      416.98          NaN            90.0  
19997     1636.90          NaN           164.0  
19998      227.88          NaN            28.0  
19999     1775.81          NaN            38.0  

[20000 rows x 13 columns]

In [101]:
merged = merged.drop(['product_id', 'brand', 'product_line', 'product_class', 'product_size', 'Unnamed: 11'], axis=1)
merged.head()

transaction_id  customer_id transaction_date online_order order_status   
0               1         2950       25.02.2017        False     Approved  \
1               2         3120       21.05.2017         True     Approved   
2               3          402       16.10.2017        False     Approved   
3               4         3135       31.08.2017        False     Approved   
4               5          787       01.10.2017         True     Approved   

   list_price  new_product_id  
0       71.49            22.0  
1     2091.47            23.0  
2     1793.43            83.0  
3     1198.46           165.0  
4     1765.30           148.0

In [102]:
merged.to_csv('data/merged.csv', index=False, sep=';')