In [1]:
import numpy as np

### Генерация `float`

Самой «базовой» функцией в нём можно считать функцию `rand`. По умолчанию она генерирует число с плавающей точкой между 0 (включительно) и 1 (не включительно):

In [2]:
np.random.rand()

0.3899878036229759

In [3]:
np.random.rand(5)

array([0.31343846, 0.49294999, 0.38189513, 0.38739978, 0.63038269])

In [4]:
np.random.rand(2, 3)
# Функция rand может принимать неограниченное число целых чисел для задания формы массива

array([[0.61799647, 0.70431522, 0.04212298],
       [0.40269287, 0.75117646, 0.15786728]])

In [5]:
np.random.uniform(0.5, 0.75, size = 5) # равномерное распределение

array([0.50464372, 0.54811831, 0.6055944 , 0.60141472, 0.71905959])

### Генерация `int`

In [6]:
np.random.randint(4, size=(2,3))

array([[3, 0, 2],
       [1, 3, 1]])

In [10]:
np.random.randint(4, 8, size=(2,3))

array([[4, 5, 5],
       [4, 7, 4]])

Задать `seed` в NumPy можно с помощью функции `np.random.seed(<np.uint32>)`

### Генерация выборок

In [ ]:
arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr)) # перемешивание массива
# None
arr
# array([0, 5, 1, 3, 2, 4])

In [ ]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist) # перемешивание массива без изменения исходного
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']

In [11]:
np.random.permutation(10)

array([2, 5, 8, 4, 1, 7, 0, 3, 6, 9])

Чтобы получить случайный набор объектов из массива, используется функция `random.choice`:

In [13]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size = 2, replace = False)
# replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут)

print(choice)

['Kate' 'John']
