In [1]:
import numpy as np

### Действия с векторами

In [2]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [3]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [5]:
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [7]:
vec1 * 4

array([ 8., 16., 28., 10.])

In [6]:
vec1 > vec2

array([False, False,  True, False])

In [8]:
vec1 <= 26

array([ True,  True,  True,  True])

### Продвинутые операции с векторами

**Длина вектора**, то есть расстояние между его началом и концом, [в евклидовом пространстве] вычисляется как квадратный корень из суммы квадратов всех его координат.

In [9]:
vec = np.array([3, 4])
length = np.linalg.norm(vec)
print(length)

5.0


**Расстояние между двумя векторами**, то есть расстояние между их концами, [в евклидовом пространстве] вычисляется как квадратный корень из суммы квадратов разностей соответствующих координат.

In [10]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702

**Скалярным произведением** двух векторов называют сумму произведений их соответствующих координат. Равенство скалярного произведения нулю означает **перпендикулярность** рассматриваемых векторов.

In [11]:
scalar_product = np.dot(vec1, vec2)
scalar_product

47

### Базовые статистические функции для векторов

Функции `np.min` и `np.max` позволяют находить максимальное и минимальное значение в векторе. Их можно записывать как в виде `np.min(<vector>)`, так и в виде `<vector>.min()`

In [ ]:
vec = np.array([2,7,18,28,18,1,8,4])
vec.min()
# 1
np.max(vec)
# 28

In [13]:
vec.mean() # среднее

10.75

### Задача
Напишите функцию `min_max_dist(*vectors)`, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

In [14]:
def min_max_dist(*vectors):
    dists = list()
    for i in range(len(vectors)):
        for j in range(i+1, len(vectors)):
            dists.append(np.linalg.norm(vectors[i] - vectors[j]))
    return min(dists), max(dists)

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

min_max_dist(vec1, vec2, vec3)

(5.196152422706632, 10.392304845413264)