In [1]:
import numpy as np

### Свойства numpy-массивов

In [4]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [ ]:
arr.ndim # размерность массива
# 1
nd_arr.ndim
# 2 

In [ ]:
arr.size # общее число элементов в массиве
# 5
nd_arr.size
# 9

In [ ]:
arr.shape # форма массива
# (5,)
nd_arr.shape
# (3, 3)

In [ ]:
arr.itemsize # сколько весит в байтах каждый элемент массива
# 1
nd_arr.itemsize
# 2

### Заполнение новых массивов

In [6]:
zeros_2d = np.zeros((2, 3), dtype=np.float32)
print(zeros_2d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
np.arange(2.5, 5, 0.5, dtype=np.float16) # start, stop, step

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [9]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True) # start, stop, num
# endpoint - включается ли финальная точка
# retstep - возвращается ли шаг
print(arr, step)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ] 0.1111111111111111


### Действия с массивами

In [11]:
arr = np.arange(8)
arr.shape = (2, 4) # задание формы массива
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [13]:
arr_new = arr.reshape((1, 8)) # не изменяет форму изначального массива arr
arr_new

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [14]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order = 'F')
# order = 'C' - массив заполняется по строкам (по умолчанию)
# order = 'F' - массив заполняется по столбцам
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [16]:
arr_trans = arr_new.transpose() # транспонирование матрицы (изначальная матрица не изменяется)
# При транспонировании одномерного массива его форма не меняется
arr_trans

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

### Индексы и срезы в массиве

In [ ]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype = np.int16)

# В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца:
elem_5_3 = mystery[4, 2]

# В переменную last сохраните элемент из последней строки последнего столбца
last = mystery[-1, -1]

# В переменную line_4 сохраните строку 4
line_4 = mystery[3]

# В переменную col_2 сохраните предпоследний столбец
col_2 = mystery[:, -2]

# Из строк 2-4 (включительно) получите столбцы 3-5 (включительно)
part = mystery[1:4, 2:5]

# Сохраните в переменную rev последний столбец в обратном порядке
rev = mystery[::-1, -1]

### Сортировка одномерных массивов

**Способ 1.** Функция `np.sort(<массив>)` возвращает новый отсортированный массив:

In [18]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)

print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


**Способ 2.** Функция `<массив>.sort()` сортирует исходный массив и возвращает None:

In [19]:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())

print(arr)

None
[ 3  4 12 12 15 23 23 45]


### Работа с пропущенными данными

In [20]:
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data)
roots

C:\Users\smart\AppData\Local\Temp\ipykernel_41372\3612371969.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

`np.nan` — это отдельный представитель класса `float`

In [21]:
np.isnan(roots)

array([False, False,  True, False])

In [23]:
roots[np.isnan(roots)] = 0 # заполнение нулями значение nan
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [ ]:
import numpy as np

mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)

# Получите булевый массив с информацией о np.nan в массиве mystery
# True - значение пропущено, False - значение не пропущено
nans_index = np.isnan(mystery)

# В переменную n_nan сохраните число пропущенных значений
n_nan = sum(nans_index)

# Скопируйте массив `mystery` в массив `mystery_new`. Заполните пропущенные 
# значения в массиве `mystery_new` нулями
mystery_new = mystery.copy()
mystery_new[nans_index] = 0

# Поменяйте тип данных в массиве mystery на int32
mystery_int = np.int32(mystery)

### Задача
Напишите функцию `get_chess(a)`, которая принимает на вход длину стороны квадрата a и возвращает двумерный массив формы (a, a), заполненный 0 и 1 в шахматном порядке. В левом верхнем углу всегда должен быть ноль.

In [2]:
def get_chess(a):
    arr = np.zeros((a,a))
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr

get_chess(4)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [6]:
# задача о раскрое
A = np.array([[3, 2, 1],[1, 6, 2],[4, 1, 5]])
B = np.array([360, 300, 675])
aswer = np.linalg.solve(A, B)
aswer

array([90., 15., 60.])